### ISSUE TITLE
`npm test` and `mocha spec/` are broken 

### ISSUE THREAD

**Issue by crismali** [daytonn/jskit#6]
```
$ npm test
> jskit@3.5.0 test /Users/Michael/Development/jskit
> echo "Error: no test specified"

Error: no test specified
```

```
$ mocha spec/
/Users/Michael/Development/jskit/spec/controller_spec.js:7
    index: sinon.spy(),
           ^
ReferenceError: sinon is not defined
    at Suite.<anonymous> (/Users/Michael/Development/jskit/spec/controller_spec.js:7:12)
    at context.describe.context.context (/usr/local/lib/node_modules/mocha/lib/interfaces/bdd.js:73:10)
    at Object.<anonymous> (/Users/Michael/Development/jskit/spec/controller_spec.js:1:63)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/mocha/lib/mocha.js:172:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/local/lib/node_modules/mocha/lib/mocha.js:169:14)
    at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:356:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:359:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

Right now the only way to run the tests is to run `npm start` and visit `localhost:300/spec/`.

**Comment by crismali** [comment]
This is resolved on master
